### ISSUE TITLE
backspace issues + enter button issues on login page

### ISSUE THREAD

**Issue by zacharytyhacz** [PJSanto429/SantoOS#1]
When I start SantoOS and go to 'create account', I type stuff and then I can't backspace the very letter of my inputs. 

And also, when i press 'enter' it doesn't submit - it just adds a 'enter character' to my password

![screen](https://user-images.githubusercontent.com/38140593/198813308-96fd2cfb-ebad-44a5-8c1f-ff67cfc3206a.png)

**Comment by PJSanto429** [comment]
Hey thanks Zach, I think I know the problem.
1. the blinking cursor works by adding and removing the character '|'  which causes some errors => should be a simple fix
2. the enter functionality is not there, so it just needs to be added

I'll work on this right away
